# Лабораторная работа №1
## Выполнила студентка группы БСТ1902 Рухая М.Р.
Напишите программу для вывода фразы "Hello, Wolrd!". Написать генератор случайных матриц. Реализовать методы сортировки строк числовой матрицы. Создать публичный репозиторий на github, и запушить выполненное задание в .ipynb формате.

### Задание №1
Напишите программу для вывода фразы "Hello, Wolrd!".

In [2]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц.

In [8]:
import numpy
import random

#Ввод значений для матрицы
m=input("Введите колличество строк матрицы: ")
n=input("Введите колличество столбцов матрицы: ")
min_lim=input("Введите минимальное значение для генерируемого числа: ")
max_lim=input("Введите максимальное значение для генерируемого числа: ")

#Значения по умолчанию
if len(m)==0: m=50
if len(n)==0: n=50
if len(min_lim)==0: min_lim=-250
if len(max_lim)==0: max_lim=1017

#Генератор матрицы
matrix=numpy.zeros((int(m),int(n)))
for i in range(int(m)):
    for j in range(int(n)):
        matrix[i][j]=random.randint(int(min_lim),int(max_lim))

print(matrix)

Введите колличество строк матрицы: 10
Введите колличество столбцов матрицы: 9
Введите минимальное значение для генерируемого числа: 7
Введите максимальное значение для генерируемого числа: 100
[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы.

#### Выборка

In [26]:
def SelectionSort(matrix_old):
    matrix_sort=matrix_old.copy()
    for h in range(int(m)):
        for i in range(int(n)-1):
            min=i
            for j in range(i+1, int(n)):
                if (matrix_sort[h][j]<matrix_sort[h][min]):
                    min=j
            matrix_sort[h][i],matrix_sort[h][min]=matrix_sort[h][min],matrix_sort[h][i]
    return matrix_sort

In [27]:
print(matrix, "\n")
print(SelectionSort(matrix))

[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]] 

[[12. 22. 24. 24. 32. 57. 72. 74. 89.]
 [22. 46. 47. 60. 64. 75. 75. 76. 77.]
 [15. 41. 41. 54. 60. 61. 68. 75. 88.]
 [ 7. 11. 27. 43. 49. 55. 55. 57. 95.]
 [ 9. 12. 19. 32. 49. 60. 86. 90. 99.]
 [30. 37. 41. 47. 50. 81. 93. 98. 99.]
 [21. 28. 44. 54. 75. 88. 89. 92. 94.]
 [38. 58. 58. 70. 78. 79. 86. 93. 99.]
 [ 7.  9. 20. 52. 54. 58. 68. 80. 88.]
 [ 9. 14. 14. 37. 48. 56. 69. 90. 95.]]


#### Вставка

In [11]:
def InsertSort(matrix_old):
    matrix_sort=matrix_old.copy()
    for h in range(int(m)):
        for i in range(1, int(n)):
            temp=matrix_sort[h][i]
            j=i-1
            while (j>=0 and temp<matrix_sort[h][j]):
                matrix_sort[h][j+1]=matrix_sort[h][j]
                j-=1
            matrix_sort[h][j+1]=temp
    return matrix_sort

In [12]:
print(matrix, "\n")
print(InsertSort(matrix))

[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]] 

[[12. 22. 24. 24. 32. 57. 72. 74. 89.]
 [22. 46. 47. 60. 64. 75. 75. 76. 77.]
 [15. 41. 41. 54. 60. 61. 68. 75. 88.]
 [ 7. 11. 27. 43. 49. 55. 55. 57. 95.]
 [ 9. 12. 19. 32. 49. 60. 86. 90. 99.]
 [30. 37. 41. 47. 50. 81. 93. 98. 99.]
 [21. 28. 44. 54. 75. 88. 89. 92. 94.]
 [38. 58. 58. 70. 78. 79. 86. 93. 99.]
 [ 7.  9. 20. 52. 54. 58. 68. 80. 88.]
 [ 9. 14. 14. 37. 48. 56. 69. 90. 95.]]


#### Обмен

In [13]:
def BubbleSort(matrix_old):
    matrix_sort=matrix_old.copy()
    for h in range(int(m)):
        for i in range(int(n)):
            for j in range(int(n)-i-1):
                if matrix_sort[h][j+1]<matrix_sort[h][j]:
                    matrix_sort[h][j],matrix_sort[h][j+1]=matrix_sort[h][j+1],matrix_sort[h][j]
    return matrix_sort

In [14]:
print(matrix, "\n")
print(BubbleSort(matrix))

[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]] 

[[12. 22. 24. 24. 32. 57. 72. 74. 89.]
 [22. 46. 47. 60. 64. 75. 75. 76. 77.]
 [15. 41. 41. 54. 60. 61. 68. 75. 88.]
 [ 7. 11. 27. 43. 49. 55. 55. 57. 95.]
 [ 9. 12. 19. 32. 49. 60. 86. 90. 99.]
 [30. 37. 41. 47. 50. 81. 93. 98. 99.]
 [21. 28. 44. 54. 75. 88. 89. 92. 94.]
 [38. 58. 58. 70. 78. 79. 86. 93. 99.]
 [ 7.  9. 20. 52. 54. 58. 68. 80. 88.]
 [ 9. 14. 14. 37. 48. 56. 69. 90. 95.]]


#### Шелл

In [15]:
def ShellSort(matrix_old):
    matrix_sort=matrix_old.copy()
    for h in range(int(m)):
        step=int(n)//2
        while step>0:
            for i in range(int(n)):
                for j in range(i+step,int(n),step):
                    if matrix_sort[h][i]>matrix_sort[h][j]:
                        matrix_sort[h][i],matrix_sort[h][j]=matrix_sort[h][j],matrix_sort[h][i]
            step//=2
    return matrix_sort

In [16]:
print(matrix, "\n")
print(ShellSort(matrix))

[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]] 

[[12. 22. 24. 24. 32. 57. 72. 74. 89.]
 [22. 46. 47. 60. 64. 75. 75. 76. 77.]
 [15. 41. 41. 54. 60. 61. 68. 75. 88.]
 [ 7. 11. 27. 43. 49. 55. 55. 57. 95.]
 [ 9. 12. 19. 32. 49. 60. 86. 90. 99.]
 [30. 37. 41. 47. 50. 81. 93. 98. 99.]
 [21. 28. 44. 54. 75. 88. 89. 92. 94.]
 [38. 58. 58. 70. 78. 79. 86. 93. 99.]
 [ 7.  9. 20. 52. 54. 58. 68. 80. 88.]
 [ 9. 14. 14. 37. 48. 56. 69. 90. 95.]]


#### Турнирная

In [2]:
def tournament_sort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2
    
    for i, v in enumerate(arr):
        tree[index + i] = (i, v)
    
    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1) 
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

#### Быстрая

In [17]:
def QuickSort_one(matrix_old):
    matrix_sort=matrix_old.copy()
    for h in range(int(m)):
        QuickSort_two(0,int(m)-2,matrix_sort,h)
    return matrix_sort

def QuickSort_two(_first, _last, _array, row):
    first=int(_first)
    last=int(_last)
    middle=int((first+last)/2)
    
    while (first<last):
        
        while( _array[row][first] < _array[row][middle]): 
            first+=1
        while( _array[row][last] > _array[row][middle]):
            last-=1
        if(first<=last):
            _array[row][first],_array[row][last]=_array[row][last],_array[row][first]
            first+=1
            last-=1
    
    if(_first<last):
        QuickSort_two(_first,last,_array,row)
    if(first<_last):
        QuickSort_two(first,_last,_array,row)

In [18]:
print(matrix, "\n")
matrix_new=matrix.copy()
print(QuickSort_one(matrix_new))

[[74. 89. 32. 24. 72. 57. 12. 22. 24.]
 [22. 77. 47. 75. 60. 75. 76. 64. 46.]
 [41. 60. 54. 88. 75. 15. 68. 41. 61.]
 [43. 57. 95. 55.  7. 27. 55. 11. 49.]
 [12. 49. 99. 32. 60. 90. 86.  9. 19.]
 [30. 81. 93. 50. 98. 37. 41. 99. 47.]
 [94. 92. 75. 21. 54. 88. 89. 44. 28.]
 [93. 58. 70. 99. 38. 86. 58. 78. 79.]
 [ 9. 80. 52. 54. 68.  7. 58. 88. 20.]
 [95. 37. 69. 56. 48. 14. 90.  9. 14.]] 

[[12. 22. 24. 24. 32. 57. 72. 74. 89.]
 [22. 46. 47. 60. 64. 75. 75. 76. 77.]
 [15. 41. 41. 54. 60. 61. 68. 75. 88.]
 [ 7. 11. 27. 43. 49. 55. 55. 57. 95.]
 [ 9. 12. 19. 32. 49. 60. 86. 90. 99.]
 [30. 37. 41. 47. 50. 81. 93. 98. 99.]
 [21. 28. 44. 54. 75. 88. 89. 92. 94.]
 [38. 58. 70. 58. 78. 79. 86. 93. 99.]
 [ 7.  9. 20. 52. 54. 58. 68. 80. 88.]
 [ 9. 14. 14. 37. 48. 56. 69. 90. 95.]]


#### Пирамидальная

In [5]:
def heapify(arr, n, i):
    largest = i 
    l = 2 * i + 1   
    r = 2 * i + 2  
    if l < n and arr[i] < arr[l]:
        largest = l
    if r < n and arr[largest] < arr[r]:
        largest = r
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i] 
        heapify(arr, n, largest)

def heap_sort(arr):
    n = len(arr)
    for i in range(n, -1, -1):
        heapify(arr, n, i)
    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

### Вывод

##### В ходе работы выполнили следующее:
##### - Написали программу для вывода фразы "Hello, Wolrd!"; 
##### - Написали генератор случайных матриц;
##### - Реализовать методы сортировки строк числовой матрицы;
##### - Создали публичный репозиторий на github, и запушили выполненное задание в .ipynb формате.